server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://orion-backend-1027936947898.us-central1.run.app/api/;
        proxy_ssl_server_name on;
        proxy_set_header Host orion-backend-1027936947898.us-central1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}